package com.uj.appstorysautopaymanager.data.remote

import android.app.Activity
import android.content.Context
import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.uj.appstorysautopaymanager.R
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

private const val TAG = "AuthFlow"

// In-app Google sign-in with NO browser: Credential Manager shows the account picker as a bottom
// sheet, returns a Google ID token, which we federate into Firebase (signInWithCredential) so the
// existing POST /auth/firebase exchange in AuthRepositoryImpl keeps working unchanged. The Gmail
// read scope is a separate concern - see util/GmailAuthManager.
class GoogleAuthDataSource @Inject constructor(
    @ApplicationContext private val appContext: Context,
    private val credentialManager: CredentialManager,
    private val firebaseAuth: FirebaseAuth
) {

    suspend fun signIn(activity: Activity): FirebaseUser {
        // Web (server) client ID - generated by the google-services plugin from the type-3
        // oauth_client in google-services.json, so it always matches the Firebase project.
        val serverClientId = appContext.getString(R.string.default_web_client_id)
        val option = GetSignInWithGoogleOption.Builder(serverClientId).build()
        val request = GetCredentialRequest.Builder().addCredentialOption(option).build()

        val response = credentialManager.getCredential(activity, request)
        val credential = response.credential
        if (credential !is CustomCredential ||
            credential.type != GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            throw IllegalStateException("Unexpected credential type: ${credential.type}")
        }

        val googleIdToken = GoogleIdTokenCredential.createFrom(credential.data).idToken
        val firebaseCredential = GoogleAuthProvider.getCredential(googleIdToken, null)
        val user = firebaseAuth.signInWithCredential(firebaseCredential).await().user
            ?: throw IllegalStateException("Google sign-in succeeded but no Firebase user was returned")
        Log.d(TAG, "Google->Firebase sign-in ok uid=${user.uid} email=${user.email}")
        return user
    }

    suspend fun signOut() {
        firebaseAuth.signOut()
        runCatching { credentialManager.clearCredentialState(ClearCredentialStateRequest()) }
            .onFailure { Log.w(TAG, "clearCredentialState failed", it) }
    }

    fun currentUser(): FirebaseUser? = firebaseAuth.currentUser
}
